#!/bin/sh
#===============================================================================#
#  NOTA DE LICENÇA                                                              #
#                                                                               #
#  Este trabalho esta licenciado sob uma Licença Creative Commons               #
#  Atribuição: Compartilhamento pela mesma Licença 3.0 Brasil. Para ver uma     #
# copia desta licença, visite http://creativecommons.org/licenses/by/3.0/br/    #
# ou envie uma carta para Creative Commons, 171 Second Street, Suite 300,       #
# San Francisco, California 94105, USA.                                         #
# ----------------------------------------------------------------------------- #
#  Autor: Jhones Petter | jhones.petter@gmail.com em 31/01/2015                 #
#  Descrição: Função PEGA_BACKUP para download dos arquivos e limpeza           #
# do directório.                                                                #
#  Data criação: 31/01/2015                                                     #
#  Versão: 1.0 - (./pega_backup_v1.sh)                                          #
#===============================================================================#

#!/bin/sh

pega_backup() {
host_ftp="ftp.seu_ftp.com.br"
user_ftp="usuario_ftp"
pass_ftp="senha_ftp"
arqvos="*.gz"
    ftp -in << EOF
    open $host_ftp
    user $user_ftp $pass_ftp
    lcd /diretorio_local_em_seu_desktop/mysql
    cd mysql
    mget $arqvos
    mdelete $arqvos
    lcd /diretorio_local_em_seu_desktop/sites
    cd ../sites
    mget $arqvos
    mdelete $arqvos
    bye
EOF
}

pega_backup

exit